#!/usr/bin/env bash
# Sync MaaS e2e test infrastructure from opendatahub-io/models-as-a-service (remote).
# Container runtime: Podman (Docker compatible) — not required; uses git fetch only.
#
# Usage:
#   ./hack/scripts/sync-maas-e2e-tests.sh
#   MAAS_REF=main ./hack/scripts/sync-maas-e2e-tests.sh
#   MAAS_COMMIT=<sha> ./hack/scripts/sync-maas-e2e-tests.sh
#
# After sync, ai-gateway-controller-specific scripts under test/e2e/scripts/ are
# preserved (see PRESERVE_PATHS below).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

MAAS_REPO="${MAAS_REPO:-https://github.com/opendatahub-io/models-as-a-service}"
MAAS_REF="${MAAS_COMMIT:-${MAAS_REF:-main}}"

SYNC_PATHS=(
  "test/e2e/tests"
  "test/e2e/fixtures"
  "test/e2e/requirements.txt"
  "test/e2e/pyproject.toml"
  "test/e2e/README.md"
  "test/e2e/smoke.sh"
  "test/e2e/run-tests-quick.sh"
  "test/e2e/scripts/auth_utils.sh"
  "test/e2e/scripts/deploy-models.sh"
  "test/e2e/scripts/setup-test-tokens.sh"
  "test/.gitignore"
  "scripts"
  "deployment"
  "docs/samples"
  ".github/hack"
)

PRESERVE_PATHS=(
  "test/e2e/scripts/prow_run_ai_gateway_controller_test.sh"
  "test/e2e/scripts/run_e2e_tests.sh"
  "test/e2e/scripts/deploy-ai-gateway-controller.sh"
  "test/e2e/scripts/deploy-platform.sh"
  "test/e2e/scripts/maas-image-defaults.sh"
)

MANIFEST_FILE="${PROJECT_ROOT}/test/.maas-sync-manifest"

fetch_maas() {
  local tmp_dir
  tmp_dir="$(mktemp -d -t maas-e2e-sync.XXXXXXXXXX)"
  trap 'rm -rf "${tmp_dir}"' RETURN

  echo "Fetching ${MAAS_REPO}@${MAAS_REF} ..."
  git -C "${tmp_dir}" init -q
  git -C "${tmp_dir}" remote add origin "${MAAS_REPO}"
  git -C "${tmp_dir}" fetch --depth 1 -q origin "${MAAS_REF}"
  git -C "${tmp_dir}" checkout -q FETCH_HEAD

  local resolved_commit
  resolved_commit="$(git -C "${tmp_dir}" rev-parse HEAD)"
  echo "Resolved MaaS commit: ${resolved_commit}"

  for rel in "${SYNC_PATHS[@]}"; do
    local src="${tmp_dir}/${rel}"
    local dst="${PROJECT_ROOT}/${rel}"
    if [[ ! -e "${src}" ]]; then
      echo "ERROR: missing path in MaaS checkout: ${rel}" >&2
      exit 1
    fi
    echo "Syncing ${rel} ..."
    rm -rf "${dst}"
    mkdir -p "$(dirname "${dst}")"
    cp -a "${src}" "${dst}"
  done

  # cp -a from git checkout may drop +x on shell scripts
  find "${PROJECT_ROOT}/scripts" "${PROJECT_ROOT}/.github/hack" -name '*.sh' -exec chmod +x {} + 2>/dev/null || true

  cat >"${MANIFEST_FILE}" <<EOF
# Auto-generated by hack/scripts/sync-maas-e2e-tests.sh — do not edit by hand.
maas_repo=${MAAS_REPO}
maas_commit=${resolved_commit}
maas_ref=${MAAS_REF}
synced_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF
  echo "Wrote ${MANIFEST_FILE}"
}

preserve_local_scripts() {
  for rel in "${PRESERVE_PATHS[@]}"; do
    if [[ ! -f "${PROJECT_ROOT}/${rel}" ]]; then
      echo "WARNING: expected local script missing (create before sync): ${rel}" >&2
    fi
  done
}

preserve_local_scripts
fetch_maas
"${SCRIPT_DIR}/patch-maas-deploy-for-aigc.sh"
echo "MaaS e2e sync complete."
